import "./globals.scss";
import { Inter } from "next/font/google";
import { Providers } from "../app/redux/provider";
import Navbar from "./components/Navbar";
import CartContainer from "./components/CartContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {/* <CartContainer /> */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
